### PR TITLE
basic github integration - get user repos, get repo languages

### PR DESCRIPTION
**Pull request by idiglove**
Screen Shot 2021-09-20 at 8 10 10 PM

@cnp0 lemme know what else we need to integrate on this PR

### CODE REVIEW

**Comment by cnp0** [comment]
I think you mentioned we were gunna rename solana_mint. I'll let you take the lead on what makes most sense to call it. Also maybe this is something I'm not understanding, but do github *features* need to be in this auth service/server or should we put this in our `web` src?

**Comment by idiglove** [comment]
> I think you mentioned we were gunna rename solana_mint. I'll let you take the lead on what makes most sense to call it. Also maybe this is something I'm not understanding, but do github _features_ need to be in this auth service/server or should we put this in our `web` src?

we can do two ways -> 
1) put react in web folder and put solana_mint in server/backend folder
2) move solana_mint to new repo and name int repomint-backend - this is the cleaner approach i think, i was just testing stuff and trying to make things work thats why i added on same repo

**Comment by cnp0** [comment]
tbh i like 2 almost always. i just didnt want to complicate things because some people are more used to having everything in one spot. id love to do this

- github.com/repomint/repomint-web
- github.com/repomint/repomint-auth
- github.com/repomint/repomint-mint
- github.com/repomint/repomint-art

or something along those lines.

**Comment by idiglove** [comment]
lets do that :)

**Comment by idiglove** [comment]
i'll merge this now, and let you clean up the repos

**Comment by cnp0** [comment]
> 
> 
> i'll merge this now, and let you clean up the repos

should i do solana_mint too?

**Comment by cnp0** [comment]
ill give @Pfed-prog some time to transfer his repo before i create `repomint-art`. i want to give him a chance to contribute his work as-is so he gets credit.

**Comment by idiglove** [comment]
> > i'll merge this now, and let you clean up the repos
> 
> should i do solana_mint too?

yes thats basically the repomint_auth
you can move the index.js to somewhere else if you'd want, thats the initial work ive done for minting tokens

**Comment by cnp0** [comment]
> yes thats basically the repomint_auth
> you can move the index.js to somewhere else if you'd want, thats the initial work ive done for minting tokens

yup! just making sure we dont double up

**Pull request merged**
